global:
  imageRegistry: ''
  imagePullSecrets: []
  storageClass: ''

app:
  name: mieszkaniownik
  version: 1.0.0

backend:
  enabled: true
  name: backend
  replicaCount: 2

  image:
    repository: mieszkaniownik-backend
    tag: 'latest'
    pullPolicy: Never

  service:
    type: ClusterIP
    port: 5001
    targetPort: 5001
    name: http

  env:
    NODE_ENV: production
    PORT: '5001'
    REDIS_HOST: redis
    REDIS_PORT: '6379'

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  healthChecks:
    enabled: true
    livenessProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  revisionHistoryLimit: 5

frontend:
  enabled: true
  name: frontend
  replicaCount: 2

  image:
    repository: mieszkaniownik-frontend
    tag: 'latest'
    pullPolicy: Never

  service:
    type: ClusterIP
    port: 80
    targetPort: 5173

  env:
    NODE_ENV: production
    PORT: '5173'

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  healthChecks:
    enabled: true
    livenessProbe:
      httpGet:
        path: /
        port: 5173
      initialDelaySeconds: 30
      periodSeconds: 15
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 5173
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  revisionHistoryLimit: 5

redis:
  enabled: true
  image:
    repository: redis
    tag: '7-alpine'
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 6379
    targetPort: 6379

  persistence:
    enabled: true
    size: 1Gi
    storageClass: 'standard'

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

database:
  postgresql:
    enabled: false
    auth:
      existingSecret: 'postgres-credentials'
      userKey: 'username'
      passwordKey: 'password'
      postgresPassword: ''
      username: ''
      password: ''
      database: 'mieszkaniownik'
    primary:
      persistence:
        enabled: true
        size: 2Gi
        storageClass: 'standard'
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi

  custom:
    enabled: true
    image:
      repository: postgres
      tag: '13'
      pullPolicy: IfNotPresent

    persistence:
      enabled: true
      size: 2Gi
      storageClass: 'standard'

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

databaseJobs:
  migrate:
    enabled: true
    image:
      repository: mieszkaniownik-backend
      tag: 'latest'
      pullPolicy: Never
    backoffLimit: 5
    restartPolicy: Never

  seed:
    enabled: true
    image:
      repository: mieszkaniownik-backend
      tag: 'latest'
      pullPolicy: Never
    backoffLimit: 5
    restartPolicy: Never

secrets:
  postgresql:
    existingSecret: 'postgres-credentials'
    userKey: 'username'
    passwordKey: 'password'
    POSTGRES_USER: ''
    POSTGRES_PASSWORD: ''

config: {}

ingress:
  enabled: false
  className: 'nginx'
  annotations: {}
  hosts:
    - host: mieszkaniownik.local
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api
          pathType: Prefix
          service: backend
  tls: []

autoscaling:
  backend:
    enabled: false
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    targetDeployment: 'mieszkaniownik-prod-mieszkaniownik-chart-backend'

  frontend:
    enabled: false
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    targetDeployment: 'mieszkaniownik-prod-mieszkaniownik-chart-frontend'

serviceAccount:
  create: true
  annotations: {}
  name: ''

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}

networkPolicy:
  enabled: false
