version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mieszkaniownik-backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/prisma:/app/prisma
    networks:
      - mieszkaniownik-net
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:5001/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mieszkaniownik-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/.env
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - mieszkaniownik-net
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: mieszkaniownik-db
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-mieszkaniownik}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mieszkaniownik-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: mieszkaniownik-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mieszkaniownik-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  mieszkaniownik-net:
    driver: bridge
