apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mieszkaniownik-dev
  name: mieszkaniownik-dev-full-access
  labels:
    app: mieszkaniownik
    rbac-type: full-access
    environment: dev
rules:
  - apiGroups: ['']
    resources:
      [
        'pods',
        'services',
        'configmaps',
        'secrets',
        'persistentvolumeclaims',
        'endpoints',
      ]
    verbs: ['*']

  - apiGroups: ['apps']
    resources: ['deployments', 'replicasets', 'statefulsets', 'daemonsets']
    verbs: ['*']

  - apiGroups: ['networking.k8s.io']
    resources: ['ingresses', 'networkpolicies']
    verbs: ['*']

  - apiGroups: ['autoscaling']
    resources: ['horizontalpodautoscalers']
    verbs: ['*']

  - apiGroups: ['batch']
    resources: ['jobs', 'cronjobs']
    verbs: ['*']

  - apiGroups: ['']
    resources: ['pods/log', 'pods/exec', 'pods/portforward', 'pods/attach']
    verbs: ['get', 'list', 'create']

  - apiGroups: ['']
    resources: ['events']
    verbs: ['get', 'list', 'watch']

  - apiGroups: ['metrics.k8s.io']
    resources: ['pods', 'nodes']
    verbs: ['get', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mieszkaniownik-prod
  name: mieszkaniownik-prod-read-only
  labels:
    app: mieszkaniownik
    rbac-type: read-only
    environment: prod
rules:
  - apiGroups: ['']
    resources:
      ['pods', 'services', 'configmaps', 'endpoints', 'persistentvolumeclaims']
    verbs: ['get', 'list', 'watch']

  - apiGroups: ['apps']
    resources: ['deployments', 'replicasets', 'statefulsets', 'daemonsets']
    verbs: ['get', 'list', 'watch']

  - apiGroups: ['networking.k8s.io']
    resources: ['ingresses', 'networkpolicies']
    verbs: ['get', 'list', 'watch']

  - apiGroups: ['autoscaling']
    resources: ['horizontalpodautoscalers']
    verbs: ['get', 'list', 'watch']

  - apiGroups: ['batch']
    resources: ['jobs', 'cronjobs']
    verbs: ['get', 'list', 'watch']

  - apiGroups: ['']
    resources: ['pods/log']
    verbs: ['get', 'list']

  - apiGroups: ['']
    resources: ['events']
    verbs: ['get', 'list', 'watch']

  - apiGroups: ['metrics.k8s.io']
    resources: ['pods', 'nodes']
    verbs: ['get', 'list']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mieszkaniownik-developers-dev-binding
  namespace: mieszkaniownik-dev
  labels:
    app: mieszkaniownik
    environment: dev
subjects:
  - kind: User
    name: wsparcie@mieszkaniownik.com
    apiGroup: rbac.authorization.k8s.io

  - kind: Group
    name: mieszkaniownik-developers
    apiGroup: rbac.authorization.k8s.io

  - kind: ServiceAccount
    name: dev-ci-sa
    namespace: mieszkaniownik-dev

roleRef:
  kind: Role
  name: mieszkaniownik-dev-full-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mieszkaniownik-developers-prod-binding
  namespace: mieszkaniownik-prod
  labels:
    app: mieszkaniownik
    environment: prod
subjects:
  - kind: User
    name: wsparcie@mieszkaniownik.com
    apiGroup: rbac.authorization.k8s.io

  - kind: Group
    name: mieszkaniownik-developers
    apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: Role
  name: mieszkaniownik-prod-read-only
  apiGroup: rbac.authorization.k8s.io
